import { NextRequest, NextResponse } from "next/server";
import {
  CaptionError,
  FORMATS,
  fetchCaptions,
  fetchVideoInfo,
  formatCues,
  type CaptionFormat,
  type CaptionTrack,
} from "@/lib/youtubeCaptions.mjs";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

/** حدّ بسيط في الذاكرة يمنع استخدام الواجهة كوكيل مفتوح ليوتيوب. */
const RATE_LIMIT = { windowMs: 60_000, max: 12 };
const hits = new Map<string, number[]>();

function rateLimited(key: string) {
  const now = Date.now();
  const recent = (hits.get(key) ?? []).filter((at) => now - at < RATE_LIMIT.windowMs);
  recent.push(now);
  hits.set(key, recent);

  // تنظيف دوري حتى لا تنمو الخريطة بلا حدّ.
  if (hits.size > 500) {
    for (const [ip, times] of hits) {
      if (!times.some((at) => now - at < RATE_LIMIT.windowMs)) hits.delete(ip);
    }
  }

  return recent.length > RATE_LIMIT.max;
}

const STATUS: Record<string, number> = {
  invalid_input: 400,
  bad_format: 400,
  unavailable: 403,
  no_captions: 404,
  empty_track: 404,
  fetch_failed: 502,
};

/** نُخفي baseUrl الموقّع — الواجهة لا تحتاجه. */
function publicTracks(tracks: CaptionTrack[]) {
  return tracks.map(({ lang, name, auto, translatable }) => ({ lang, name, auto, translatable }));
}

/**
 * GET /api/youtube/captions?url=…
 *   list=1                 قائمة مسارات الترجمة المتاحة فقط
 *   lang=ar  auto=prefer|skip  translate=en
 *   format=txt|srt|vtt     يعيد ملفًا نصيًا بدل JSON (مع download=1 كمرفق)
 */
export async function GET(req: NextRequest) {
  const params = req.nextUrl.searchParams;
  const target = params.get("url")?.trim();

  if (!target) {
    return NextResponse.json({ error: "missing_url" }, { status: 400 });
  }

  const ip = req.headers.get("x-forwarded-for")?.split(",")[0].trim() || "local";
  if (rateLimited(ip)) {
    return NextResponse.json({ error: "rate_limited" }, { status: 429 });
  }

  const format = (params.get("format")?.toLowerCase() || "json") as CaptionFormat;
  if (!FORMATS.includes(format)) {
    return NextResponse.json({ error: "bad_format" }, { status: 400 });
  }

  const auto = params.get("auto");
  const options = {
    lang: params.get("lang")?.trim() || "en",
    translate: params.get("translate")?.trim() || null,
    auto: auto === "prefer" ? true : auto === "skip" ? false : null,
    signal: req.signal,
  };

  try {
    if (params.get("list") === "1") {
      const info = await fetchVideoInfo(target, { signal: req.signal });
      return NextResponse.json({ ...info, tracks: publicTracks(info.tracks) });
    }

    const result = await fetchCaptions(target, options);
    const meta = {
      videoId: result.videoId,
      title: result.title,
      channel: result.channel,
      language: result.language,
      autoGenerated: result.autoGenerated,
    };

    if (format !== "json") {
      const body = formatCues(result.cues, format, {
        timestamps: params.get("timestamps") === "1",
        meta,
      });
      const headers: Record<string, string> = { "content-type": "text/plain; charset=utf-8" };
      if (params.get("download") === "1") {
        headers["content-disposition"] = `attachment; filename="${result.videoId}.${format}"`;
      }
      return new NextResponse(body, { headers });
    }

    return NextResponse.json({ ...meta, tracks: publicTracks(result.tracks), cues: result.cues });
  } catch (err) {
    if (err instanceof CaptionError) {
      return NextResponse.json({ error: err.code, detail: err.message }, { status: STATUS[err.code] ?? 500 });
    }
    if (err instanceof Error && err.name === "AbortError") {
      return NextResponse.json({ error: "timeout" }, { status: 504 });
    }
    console.error("youtube captions GET failed:", err);
    return NextResponse.json({ error: "unexpected" }, { status: 500 });
  }
}
