"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { formatCues, shortTimecode, type CaptionFormat } from "@/lib/youtubeCaptions.mjs";

type Track = { lang: string; name: string; auto: boolean; translatable: boolean };
type Cue = { start: number; end: number; text: string };
type Result = {
  videoId: string;
  title: string | null;
  channel: string | null;
  language: string;
  autoGenerated: boolean;
  tracks: Track[];
  cues: Cue[];
};

const ERRORS: Record<string, string> = {
  missing_url: "الرجاء لصق رابط الفيديو.",
  invalid_input: "لم أتعرّف على رابط يوتيوب في ما أدخلته.",
  no_captions: "لا توجد ترجمات منشورة لهذا الفيديو.",
  empty_track: "مسار الترجمة وصل فارغًا من يوتيوب.",
  unavailable: "يوتيوب يرفض عرض هذا الفيديو (خاص أو محذوف أو مقيّد بالعمر).",
  blocked:
    "يوتيوب يحجب خادم الموقع ويطلب تسجيل دخول للتأكد أنه ليس روبوتًا — وهذا قيد على عنوان الخادم لا على الفيديو. " +
    "شغّل السكربت من جهازك للحصول على النص: npm run captions -- <الرابط>",
  fetch_failed: "تعذّر الوصول إلى يوتيوب. حاول مرة أخرى بعد قليل.",
  rate_limited: "طلبات كثيرة خلال وقت قصير. انتظر دقيقة ثم أعد المحاولة.",
  timeout: "انتهت مهلة الطلب قبل أن يردّ يوتيوب.",
  bad_format: "صيغة غير مدعومة.",
  unexpected: "حدث خطأ غير متوقع.",
};

const FORMAT_LABELS: { id: CaptionFormat; label: string }[] = [
  { id: "txt", label: "نص" },
  { id: "srt", label: "SRT" },
  { id: "vtt", label: "VTT" },
  { id: "json", label: "JSON" },
];

const TRANSLATE_TO = [
  { code: "", label: "بدون ترجمة آلية" },
  { code: "ar", label: "العربية" },
  { code: "en", label: "الإنجليزية" },
  { code: "fr", label: "الفرنسية" },
  { code: "es", label: "الإسبانية" },
  { code: "de", label: "الألمانية" },
  { code: "tr", label: "التركية" },
  { code: "ur", label: "الأردية" },
  { code: "hi", label: "الهندية" },
  { code: "id", label: "الإندونيسية" },
  { code: "ru", label: "الروسية" },
];

const inputBase =
  "w-full rounded-xl border border-gray-200 bg-white px-3.5 py-2.5 text-sm text-gray-800 " +
  "placeholder:text-gray-300 outline-none transition focus:border-[#16b1a1] focus:ring-4 focus:ring-[#16b1a1]/10 " +
  "disabled:cursor-not-allowed disabled:bg-gray-50 disabled:text-gray-400";

function trackLabel(track: Track) {
  return `${track.name} · ${track.lang}${track.auto ? " (تلقائية)" : ""}`;
}

export default function CaptionsApp() {
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [reason, setReason] = useState<string | null>(null);
  const [result, setResult] = useState<Result | null>(null);

  const [format, setFormat] = useState<CaptionFormat>("txt");
  const [timestamps, setTimestamps] = useState(true);
  const [translate, setTranslate] = useState("");
  const [copied, setCopied] = useState(false);

  const inFlight = useRef<AbortController | null>(null);
  useEffect(() => () => inFlight.current?.abort(), []);

  async function load(target: string, opts: { lang?: string; auto?: string; translate?: string } = {}) {
    const cleaned = target.trim();
    if (!cleaned) {
      setError(ERRORS.missing_url);
      return;
    }

    inFlight.current?.abort();
    const controller = new AbortController();
    inFlight.current = controller;

    setLoading(true);
    setError(null);
    setReason(null);

    const query = new URLSearchParams({ url: cleaned, lang: opts.lang ?? "any" });
    if (opts.auto) query.set("auto", opts.auto);
    if (opts.translate) query.set("translate", opts.translate);

    try {
      const res = await fetch(`/api/youtube/captions?${query}`, { signal: controller.signal });
      const payload = await res.json();

      if (!res.ok) {
        setError(ERRORS[payload?.error] ?? ERRORS.unexpected);
        setReason(payload?.reason ?? null);
        setResult(null);
        return;
      }

      setReason(null);

      setResult(payload as Result);
    } catch (err) {
      if ((err as Error).name === "AbortError") return;
      setError(ERRORS.fetch_failed);
      setResult(null);
    } finally {
      if (inFlight.current === controller) setLoading(false);
    }
  }

  /** تبديل المسار: نثبّت اللغة ونخبر الخادم إن كانت النسخة تلقائية أم يدوية. */
  function switchTrack(lang: string, nextTranslate = translate) {
    if (!result) return;
    const track = result.tracks.find((t) => t.lang === lang);
    void load(result.videoId, {
      lang,
      auto: track?.auto ? "prefer" : "skip",
      translate: nextTranslate,
    });
  }

  const meta = useMemo(
    () =>
      result && {
        videoId: result.videoId,
        title: result.title,
        channel: result.channel,
        language: result.language,
        autoGenerated: result.autoGenerated,
      },
    [result],
  );

  const output = useMemo(
    () => (result ? formatCues(result.cues, format, { timestamps, meta: meta ?? {} }) : ""),
    [result, format, timestamps, meta],
  );

  async function copyAll() {
    try {
      await navigator.clipboard.writeText(output);
      setCopied(true);
      setTimeout(() => setCopied(false), 1800);
    } catch {
      setError("المتصفح منع النسخ التلقائي — حدّد النص وانسخه يدويًا.");
    }
  }

  function download() {
    if (!result) return;
    const blob = new Blob([output], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${result.videoId}-${result.language}.${format}`;
    link.click();
    URL.revokeObjectURL(url);
  }

  const activeTrackLang = result?.tracks.some((t) => t.lang === result.language)
    ? result.language
    : (result?.tracks[0]?.lang ?? "");

  return (
    <div className="min-h-screen bg-gray-50/60 px-4 py-10">
      <div className="mx-auto w-full max-w-3xl">
        <header className="mb-6 text-center">
          <h1 className="text-2xl font-extrabold text-gray-800 sm:text-3xl">استخراج ترجمات يوتيوب</h1>
          <p className="mt-2 text-sm font-medium text-gray-500">
            الصق رابط أي فيديو لتحصل على نصّه كاملًا، أو كملف ترجمة SRT / VTT.
          </p>
        </header>

        <form
          className="flex flex-col gap-3 rounded-2xl border border-gray-100 bg-white p-4 shadow-sm sm:flex-row"
          onSubmit={(e) => {
            e.preventDefault();
            setTranslate("");
            void load(input);
          }}
        >
          <input
            dir="ltr"
            className={`${inputBase} text-left`}
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="https://youtu.be/..."
            aria-label="رابط الفيديو"
          />
          <button
            type="submit"
            disabled={loading}
            className="shrink-0 rounded-xl bg-[#16b1a1] px-6 py-2.5 text-sm font-bold text-white transition hover:bg-[#129c8e] disabled:cursor-not-allowed disabled:bg-gray-300"
          >
            {loading ? "جارٍ الاستخراج…" : "استخراج"}
          </button>
        </form>

        {error && (
          <div className="mt-4 rounded-xl border border-red-100 bg-red-50 px-4 py-3">
            <p className="text-sm font-bold leading-relaxed text-red-600">{error}</p>
            {reason && (
              <p dir="ltr" className="mt-2 text-left font-mono text-[11px] leading-relaxed text-red-400">
                {reason}
              </p>
            )}
          </div>
        )}

        {result && (
          <section className="mt-6 overflow-hidden rounded-2xl border border-gray-100 bg-white shadow-sm">
            <div className="border-b border-gray-100 p-4">
              <h2 className="text-base font-extrabold text-gray-800">{result.title ?? result.videoId}</h2>
              <p className="mt-1 text-[13px] font-medium text-gray-500">
                {result.channel ? `${result.channel} · ` : ""}
                {result.cues.length} سطر ·{" "}
                {result.autoGenerated ? "ترجمة تلقائية" : "ترجمة منشورة"} · {result.language}
              </p>
            </div>

            <div className="flex flex-wrap items-end gap-3 border-b border-gray-100 bg-gray-50/60 p-4">
              <label className="block">
                <span className="mb-1.5 block text-[13px] font-bold text-gray-600">المسار</span>
                <select
                  className={`${inputBase} w-auto min-w-44`}
                  value={activeTrackLang}
                  disabled={loading}
                  onChange={(e) => switchTrack(e.target.value)}
                >
                  {result.tracks.map((track) => (
                    <option key={`${track.lang}-${track.auto}`} value={track.lang}>
                      {trackLabel(track)}
                    </option>
                  ))}
                </select>
              </label>

              <label className="block">
                <span className="mb-1.5 block text-[13px] font-bold text-gray-600">ترجمة آلية</span>
                <select
                  className={`${inputBase} w-auto min-w-44`}
                  value={translate}
                  disabled={loading}
                  onChange={(e) => {
                    setTranslate(e.target.value);
                    switchTrack(activeTrackLang, e.target.value);
                  }}
                >
                  {TRANSLATE_TO.map((item) => (
                    <option key={item.code} value={item.code}>
                      {item.label}
                    </option>
                  ))}
                </select>
              </label>

              <div className="flex flex-1 flex-wrap items-center justify-end gap-2">
                <div className="flex rounded-xl border border-gray-200 bg-white p-1">
                  {FORMAT_LABELS.map((item) => (
                    <button
                      key={item.id}
                      type="button"
                      onClick={() => setFormat(item.id)}
                      className={`rounded-lg px-3 py-1.5 text-[13px] font-bold transition ${
                        format === item.id ? "bg-[#16b1a1] text-white" : "text-gray-500 hover:text-gray-700"
                      }`}
                    >
                      {item.label}
                    </button>
                  ))}
                </div>

                <button
                  type="button"
                  onClick={copyAll}
                  className="rounded-xl border border-gray-200 px-4 py-2 text-[13px] font-bold text-gray-600 transition hover:border-[#16b1a1] hover:text-[#16b1a1]"
                >
                  {copied ? "تم النسخ" : "نسخ"}
                </button>
                <button
                  type="button"
                  onClick={download}
                  className="rounded-xl border border-gray-200 px-4 py-2 text-[13px] font-bold text-gray-600 transition hover:border-[#16b1a1] hover:text-[#16b1a1]"
                >
                  تنزيل
                </button>
              </div>

              {format === "txt" && (
                <label className="flex w-full items-center gap-2 text-[13px] font-bold text-gray-600">
                  <input
                    type="checkbox"
                    className="size-4 accent-[#16b1a1]"
                    checked={timestamps}
                    onChange={(e) => setTimestamps(e.target.checked)}
                  />
                  إظهار التوقيتات
                </label>
              )}
            </div>

            {format === "txt" ? (
              <ol className="max-h-[32rem] divide-y divide-gray-50 overflow-y-auto">
                {result.cues.map((cue, index) => (
                  <li key={index} className="flex gap-3 px-4 py-2.5 hover:bg-gray-50/70">
                    {timestamps && (
                      <a
                        href={`https://youtu.be/${result.videoId}?t=${Math.floor(cue.start / 1000)}`}
                        target="_blank"
                        rel="noreferrer"
                        className="shrink-0 pt-0.5 font-mono text-[12px] font-bold text-[#16b1a1] hover:underline"
                        dir="ltr"
                      >
                        {shortTimecode(cue.start)}
                      </a>
                    )}
                    <span className="text-[15px] leading-relaxed text-gray-700">{cue.text}</span>
                  </li>
                ))}
              </ol>
            ) : (
              <pre
                dir="ltr"
                className="max-h-[32rem] overflow-auto bg-gray-900/95 p-4 text-left font-mono text-[12.5px] leading-relaxed text-gray-100"
              >
                {output}
              </pre>
            )}
          </section>
        )}

        <p className="mt-6 text-center text-[12px] font-medium text-gray-400">
          تعمل الأداة مع الفيديوهات التي تحتوي ترجمات منشورة أو تلقائية فقط. النصوص ملك لأصحابها.
        </p>
      </div>
    </div>
  );
}
