/**
 * استخراج ترجمات فيديوهات يوتيوب — النواة المشتركة بين واجهة الموقع وسكربت الطرفية.
 *
 * لا يحتاج مفتاح API: يقرأ مسارات الترجمة من حمولة مشغّل يوتيوب نفسه.
 * الملف خالٍ من واجهات Node الخاصة (fetch فقط) ليعمل داخل Route Handlers.
 */

/** @typedef {{ lang: string, name: string, auto: boolean, translatable: boolean, baseUrl: string }} CaptionTrack */
/** @typedef {{ start: number, end: number, text: string }} Cue */
/** @typedef {{ videoId: string, title: string | null, channel: string | null, tracks: CaptionTrack[] }} VideoInfo */
/** @typedef {VideoInfo & { language: string, autoGenerated: boolean, cues: Cue[] }} CaptionResult */
/** @typedef {"txt" | "srt" | "vtt" | "json"} CaptionFormat */

/** @type {readonly CaptionFormat[]} */
export const FORMATS = ["txt", "srt", "vtt", "json"];

const REQUEST_TIMEOUT_MS = 15000;

const BROWSER_HEADERS = {
  "user-agent":
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36",
  "accept-language": "en-US,en;q=0.9",
};

/** خطأ معروف يحمل رمزًا تترجمه الواجهة إلى رسالة للمستخدم. */
export class CaptionError extends Error {
  /**
   * @param {"invalid_input" | "unavailable" | "no_captions" | "fetch_failed" | "empty_track" | "bad_format"} code
   * @param {string} message
   */
  constructor(code, message) {
    super(message);
    this.name = "CaptionError";
    this.code = code;
  }
}

/** مهلة لكل طلب، مع احترام إشارة الإلغاء القادمة من المتصل. */
function withTimeout(signal) {
  const timeout = AbortSignal.timeout(REQUEST_TIMEOUT_MS);
  return signal ? AbortSignal.any([signal, timeout]) : timeout;
}

/* ------------------------------------------------------------ معرّف الفيديو */

/**
 * يقبل رابط يوتيوب بأي صيغة، أو المعرّف المكوّن من 11 خانة.
 * @param {string} target
 * @returns {string}
 */
export function extractVideoId(target) {
  const trimmed = String(target ?? "").trim();
  if (/^[\w-]{11}$/.test(trimmed)) return trimmed;

  let url;
  try {
    url = new URL(trimmed.includes("://") ? trimmed : `https://${trimmed}`);
  } catch {
    throw new CaptionError("invalid_input", `Could not read a video id from: ${trimmed}`);
  }

  const host = url.hostname.replace(/^www\.|^m\./, "");
  if (host === "youtu.be") {
    const id = url.pathname.slice(1).split("/")[0];
    if (/^[\w-]{11}$/.test(id)) return id;
  }

  if (host.endsWith("youtube.com") || host.endsWith("youtube-nocookie.com")) {
    const v = url.searchParams.get("v");
    if (v && /^[\w-]{11}$/.test(v)) return v;

    const match = url.pathname.match(/^\/(?:shorts|embed|live|v)\/([\w-]{11})/);
    if (match) return match[1];
  }

  throw new CaptionError("invalid_input", `Could not read a video id from: ${trimmed}`);
}

/* ------------------------------------------------------- حمولة المشغّل */

/** يقرأ كائن JSON كاملًا من نص الصفحة ابتداءً من أول قوس. */
function readJsonObject(source, from) {
  const start = source.indexOf("{", from);
  if (start === -1) return null;

  let depth = 0;
  let inString = false;
  let escaped = false;

  for (let i = start; i < source.length; i++) {
    const char = source[i];

    if (inString) {
      if (escaped) escaped = false;
      else if (char === "\\") escaped = true;
      else if (char === '"') inString = false;
      continue;
    }

    if (char === '"') inString = true;
    else if (char === "{") depth++;
    else if (char === "}" && --depth === 0) {
      try {
        return JSON.parse(source.slice(start, i + 1));
      } catch {
        return null;
      }
    }
  }

  return null;
}

async function playerResponseFromWatchPage(videoId, signal) {
  // bpctr و has_verified يتجاوزان صفحات الموافقة والتأكيد.
  const url = `https://www.youtube.com/watch?v=${videoId}&hl=en&bpctr=9999999999&has_verified=1`;
  const res = await fetch(url, {
    headers: { ...BROWSER_HEADERS, cookie: "CONSENT=YES+cb; SOCS=CAI" },
    signal: withTimeout(signal),
  });
  if (!res.ok) throw new Error(`YouTube returned HTTP ${res.status} for the watch page`);

  const html = await res.text();
  const marker = html.indexOf("ytInitialPlayerResponse");
  if (marker === -1) return null;

  return readJsonObject(html, marker);
}

async function playerResponseFromInnertube(videoId, signal) {
  // عميل الجوال يعيد مسارات الترجمة دون الحاجة لفكّ التواقيع.
  const res = await fetch("https://www.youtube.com/youtubei/v1/player", {
    method: "POST",
    headers: {
      ...BROWSER_HEADERS,
      "content-type": "application/json",
      "x-youtube-client-name": "3",
      "x-youtube-client-version": "20.10.38",
    },
    body: JSON.stringify({
      context: {
        client: {
          clientName: "ANDROID",
          clientVersion: "20.10.38",
          androidSdkVersion: 34,
          hl: "en",
          gl: "US",
        },
      },
      videoId,
      contentCheckOk: true,
      racyCheckOk: true,
    }),
    signal: withTimeout(signal),
  });
  if (!res.ok) throw new Error(`YouTube returned HTTP ${res.status} for the player API`);

  return res.json();
}

async function fetchPlayerResponse(videoId, signal) {
  const attempts = [playerResponseFromWatchPage, playerResponseFromInnertube];
  const failures = [];
  let blocked = null;

  for (const attempt of attempts) {
    let response;
    try {
      response = await attempt(videoId, signal);
    } catch (error) {
      failures.push(error instanceof Error ? error.message : String(error));
      continue;
    }

    if (response?.captions?.playerCaptionsTracklistRenderer) return response;

    const status = response?.playabilityStatus;
    if (status && status.status !== "OK") {
      blocked = status.reason || status.messages?.join(" ") || status.status;
    }
  }

  if (blocked) throw new CaptionError("unavailable", `YouTube will not serve this video: ${blocked}`);
  if (failures.length === attempts.length) {
    throw new CaptionError("fetch_failed", `Could not reach YouTube: ${failures.join("; ")}`);
  }

  throw new CaptionError("no_captions", "This video has no caption tracks (or YouTube refused to list them).");
}

/* ---------------------------------------------------------- المسارات */

/**
 * @param {unknown} playerResponse
 * @returns {CaptionTrack[]}
 */
function readTracks(playerResponse) {
  const renderer = playerResponse?.captions?.playerCaptionsTracklistRenderer;
  return (renderer?.captionTracks || []).map((track) => ({
    lang: track.languageCode,
    name:
      track.name?.simpleText ||
      track.name?.runs?.map((run) => run.text).join("") ||
      track.languageCode,
    auto: track.kind === "asr",
    translatable: Boolean(track.isTranslatable),
    baseUrl: track.baseUrl,
  }));
}

/**
 * يختار المسار الأنسب: تطابق اللغة أولًا، ثم اللهجات (en ↔ en-GB)، مع تفضيل
 * الترجمة اليدوية على الآلية ما لم يُطلب العكس.
 * @param {CaptionTrack[]} tracks
 * @param {{ lang?: string, auto?: boolean | null }} options
 * @returns {CaptionTrack}
 */
export function pickTrack(tracks, { lang = "en", auto = null } = {}) {
  let pool = tracks;
  if (auto === false) pool = pool.filter((track) => !track.auto);
  if (!pool.length) throw new CaptionError("no_captions", "No caption track matches the requested options.");

  const byPreference = (candidates) =>
    (auto === true
      ? candidates.find((track) => track.auto)
      : candidates.find((track) => !track.auto)) || candidates[0];

  if (lang && lang !== "any") {
    const wanted = lang.toLowerCase();
    const exact = pool.filter((track) => track.lang.toLowerCase() === wanted);
    if (exact.length) return byPreference(exact);

    const prefixed = pool.filter((track) => track.lang.toLowerCase().startsWith(`${wanted}-`));
    if (prefixed.length) return byPreference(prefixed);
  }

  return byPreference(pool);
}

/* ------------------------------------------------------------- الجُمل */

function decodeEntities(text) {
  return text
    .replace(/&#(\d+);/g, (_, code) => String.fromCodePoint(Number(code)))
    .replace(/&#x([\da-f]+);/gi, (_, code) => String.fromCodePoint(parseInt(code, 16)))
    .replace(/&quot;/g, '"')
    .replace(/&#39;|&apos;/g, "'")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&");
}

function cuesFromJson3(payload) {
  const cues = [];

  for (const event of payload.events || []) {
    // أحداث aAppend تكرّر نصًا صدر سابقًا في الترجمة الآلية.
    if (event.aAppend === 1 || !event.segs) continue;

    const text = event.segs
      .map((seg) => seg.utf8 || "")
      .join("")
      .replace(/\s+/g, " ")
      .trim();
    if (!text) continue;

    const start = event.tStartMs ?? 0;
    cues.push({ start, end: start + (event.dDurationMs ?? 0), text });
  }

  return cues;
}

function cuesFromXml(xml) {
  const cues = [];
  const pattern = /<text([^>]*)>([\s\S]*?)<\/text>/g;

  for (const [, attrs, body] of xml.matchAll(pattern)) {
    const start = Number(attrs.match(/\bstart="([\d.]+)"/)?.[1] ?? 0) * 1000;
    const dur = Number(attrs.match(/\bdur="([\d.]+)"/)?.[1] ?? 0) * 1000;

    // هذه الواجهة تُرمّز الكيانات مرتين ("&" تصل كـ "&amp;amp;")، فنفكّها مرتين.
    const text = decodeEntities(decodeEntities(body.replace(/<[^>]+>/g, "")))
      .replace(/\s+/g, " ")
      .trim();
    if (!text) continue;

    cues.push({ start, end: start + dur, text });
  }

  return cues;
}

/** يمنح الجُمل صفرية الطول نهاية منطقية حتى يبقى ملف SRT/VTT صالحًا. */
function closeGaps(cues) {
  return cues.map((cue, index) => {
    if (cue.end > cue.start) return cue;
    const next = cues[index + 1];
    return { ...cue, end: next ? Math.max(next.start, cue.start + 500) : cue.start + 2000 };
  });
}

/**
 * @param {CaptionTrack} track
 * @param {string | null} translate
 * @param {AbortSignal} [signal]
 * @returns {Promise<Cue[]>}
 */
async function fetchCues(track, translate, signal) {
  const url = new URL(track.baseUrl);
  if (translate) url.searchParams.set("tlang", translate);

  // json3 يحمل توقيتًا أدقّ؛ وصيغة XML القديمة هي خطة الاحتياط.
  url.searchParams.set("fmt", "json3");
  let res = await fetch(url, { headers: BROWSER_HEADERS, signal: withTimeout(signal) });
  let body = res.ok ? await res.text() : "";

  if (body.trim().startsWith("{")) {
    try {
      const cues = closeGaps(cuesFromJson3(JSON.parse(body)));
      if (cues.length) return cues;
    } catch {
      /* ننتقل إلى XML */
    }
  }

  url.searchParams.delete("fmt");
  res = await fetch(url, { headers: BROWSER_HEADERS, signal: withTimeout(signal) });
  if (!res.ok) throw new CaptionError("fetch_failed", `Caption download failed with HTTP ${res.status}`);
  body = await res.text();

  const cues = closeGaps(cuesFromXml(body));
  if (!cues.length) throw new CaptionError("empty_track", "The caption track came back empty.");
  return cues;
}

/* ------------------------------------------------------- الواجهة العليا */

/**
 * يقرأ بيانات الفيديو وقائمة مسارات الترجمة المتاحة.
 * @param {string} target رابط أو معرّف فيديو
 * @param {{ signal?: AbortSignal }} [options]
 * @returns {Promise<VideoInfo>}
 */
export async function fetchVideoInfo(target, { signal } = {}) {
  const videoId = extractVideoId(target);
  const playerResponse = await fetchPlayerResponse(videoId, signal);
  const tracks = readTracks(playerResponse);

  if (!tracks.length) throw new CaptionError("no_captions", "This video has no caption tracks.");

  return {
    videoId,
    title: playerResponse.videoDetails?.title ?? null,
    channel: playerResponse.videoDetails?.author ?? null,
    tracks,
  };
}

/**
 * يستخرج ترجمة الفيديو كاملة.
 * @param {string} target رابط أو معرّف فيديو
 * @param {{ lang?: string, auto?: boolean | null, translate?: string | null, signal?: AbortSignal }} [options]
 * @returns {Promise<CaptionResult>}
 */
export async function fetchCaptions(target, { lang = "en", auto = null, translate = null, signal } = {}) {
  const info = await fetchVideoInfo(target, { signal });
  const track = pickTrack(info.tracks, { lang, auto });
  const cues = await fetchCues(track, translate, signal);

  return {
    ...info,
    language: translate || track.lang,
    autoGenerated: track.auto,
    cues,
  };
}

/* -------------------------------------------------------------- الصيغ */

function timecode(ms, msSeparator) {
  const total = Math.max(0, Math.round(ms));
  const hours = String(Math.floor(total / 3600000)).padStart(2, "0");
  const minutes = String(Math.floor(total / 60000) % 60).padStart(2, "0");
  const seconds = String(Math.floor(total / 1000) % 60).padStart(2, "0");
  const millis = String(total % 1000).padStart(3, "0");
  return `${hours}:${minutes}:${seconds}${msSeparator}${millis}`;
}

/** توقيت مختصر للعرض: m:ss أو h:mm:ss. */
export function shortTimecode(ms) {
  const total = Math.max(0, Math.floor(ms / 1000));
  const minutes = Math.floor(total / 60);
  const seconds = String(total % 60).padStart(2, "0");
  if (minutes < 60) return `${minutes}:${seconds}`;
  return `${Math.floor(minutes / 60)}:${String(minutes % 60).padStart(2, "0")}:${seconds}`;
}

/**
 * @param {Cue[]} cues
 * @param {CaptionFormat} format
 * @param {{ timestamps?: boolean, meta?: Record<string, unknown> }} [options]
 * @returns {string}
 */
export function formatCues(cues, format, { timestamps = false, meta = {} } = {}) {
  switch (format) {
    case "txt":
      return cues
        .map((cue) => (timestamps ? `[${shortTimecode(cue.start)}] ${cue.text}` : cue.text))
        .join("\n");

    case "srt":
      return cues
        .map((cue, index) =>
          [index + 1, `${timecode(cue.start, ",")} --> ${timecode(cue.end, ",")}`, cue.text, ""].join("\n"),
        )
        .join("\n");

    case "vtt":
      return [
        "WEBVTT",
        "",
        ...cues.map((cue) => `${timecode(cue.start, ".")} --> ${timecode(cue.end, ".")}\n${cue.text}\n`),
      ].join("\n");

    case "json":
      return JSON.stringify({ ...meta, cues }, null, 2);

    default:
      throw new CaptionError("bad_format", `Unknown format: ${format}. Use txt, srt, vtt or json.`);
  }
}
